stages:
  - deploy

deploy-mainnet-railway:
  stage: deploy
  image: ubuntu
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | bash
    - RAILWAY_TOKEN=$RAILWAY_TOKEN railway link $RAILWAY_PROJECY_ID --environment production $RAILWAY_MAINNET_SERVICE_NAME

deploy-devnet-railway:
  stage: deploy
  image: ubuntu
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "devnet"'
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | bash
    - RAILWAY_TOKEN=$RAILWAY_TOKEN railway link $RAILWAY_PROJECY_ID --environment production $RAILWAY_DEVNET_SERVICE_NAME
