stages:
  - deploy

deploy-mainnet-railway:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
  variables:
    SVC_ID: $RAILWAY_MAINNET_SERVICE_NAME
  script:
    - railway up --service=$SVC_ID

deploy-mainnet-war-railway:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "mainnet-war"'
  variables:
    SVC_ID: $RAILWAY_MAINNET_WAR_SERVICE_NAME
  script:
    - railway up --service=$SVC_ID

deploy-devnet-railway:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "devnet"'
  variables:
    SVC_ID: $RAILWAY_DEVNET_SERVICE_NAME
  script:
    - railway up --service=$SVC_ID
