stages:
  - deploy

deploy-mainnet-railway:
  stage: deploy
  image: ubuntu
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://raw.githubusercontent.com/railwayapp/cli/master/v2.sh | sh
    - RAILWAY_TOKEN=$RAILWAY_TOKEN railway link $RAILWAY_PROJECY_ID
    - RAILWAY_TOKEN=$RAILWAY_TOKEN railway up --service=$RAILWAY_MAINNET_SERVICE_NAME -d

deploy-devnet-railway:
  stage: deploy
  image: ubuntu
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "devnet"'
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://raw.githubusercontent.com/railwayapp/cli/master/v2.sh | sh
    - RAILWAY_TOKEN=$RAILWAY_TOKEN railway link $RAILWAY_PROJECY_ID
    - RAILWAY_TOKEN=$RAILWAY_TOKEN railway up --service=$RAILWAY_DEVNET_SERVICE_NAME -d